version: '3'
services:
    database:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 'postgres@2023'
        ports:
            - '15432:5432'
        volumes:
            - ./postgres:/var/lib/postgresql/data
